# This is a basic workflow to help you get started with Actions

name: 'Update Bot'
 
on:
  repository_dispatch:
  workflow_dispatch:
    
jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          repository: felixonmars/dnsmasq-china-list
      - name: 'Checkout Ubuntu'
        uses: actions/checkout@v1
      - name: 'Set up Python'
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: 'Install dependencies'
        run: pip install requests
      - name: 'update'
        run: python3 ./update.py
